name: customer_io_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  openapi_generator_annotations: ^3.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  openapi_generator: ^3.3.0