import 'package:test/test.dart';
import 'package:openapi/openapi.dart';

// tests for InlineResponse20050SenderIdentities
void main() {
  final instance = InlineResponse20050SenderIdentitiesBuilder();
  // TODO add properties to the builder and call build()

  group(InlineResponse20050SenderIdentities, () {
    // The identifier of a sender.
    // int id
    test('to test the property `id`', () async {
      // TODO
    });

    // A completely unique CIO identifier.
    // String deduplicateId
    test('to test the property `deduplicateId`', () async {
      // TODO
    });

    // The name of the sender.
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // The email address of the sender.
    // String email
    test('to test the property `email`', () async {
      // TODO
    });

    // The sender name and email address in the format `name undefined<name@example.com>`.
    // String address
    test('to test the property `address`', () async {
      // TODO
    });

    // The type of sender.
    // String templateType
    test('to test the property `templateType`', () async {
      // TODO
    });

    // If true, the sender is automatically generated by Customer.io.
    // bool autoGenerated
    test('to test the property `autoGenerated`', () async {
      // TODO
    });

  });
}
