//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'inline_response20050_sender_identities.g.dart';

/// Information about a sender.
///
/// Properties:
/// * [id] - The identifier of a sender.
/// * [deduplicateId] - A completely unique CIO identifier.
/// * [name] - The name of the sender.
/// * [email] - The email address of the sender.
/// * [address] - The sender name and email address in the format `name undefined<name@example.com>`.
/// * [templateType] - The type of sender.
/// * [autoGenerated] - If true, the sender is automatically generated by Customer.io.
abstract class InlineResponse20050SenderIdentities implements Built<InlineResponse20050SenderIdentities, InlineResponse20050SenderIdentitiesBuilder> {
    /// The identifier of a sender.
    @BuiltValueField(wireName: r'id')
    int? get id;

    /// A completely unique CIO identifier.
    @BuiltValueField(wireName: r'deduplicate_id')
    String? get deduplicateId;

    /// The name of the sender.
    @BuiltValueField(wireName: r'name')
    String? get name;

    /// The email address of the sender.
    @BuiltValueField(wireName: r'email')
    String? get email;

    /// The sender name and email address in the format `name undefined<name@example.com>`.
    @BuiltValueField(wireName: r'address')
    String? get address;

    /// The type of sender.
    @BuiltValueField(wireName: r'template_type')
    InlineResponse20050SenderIdentitiesTemplateTypeEnum? get templateType;
    // enum templateTypeEnum {  email,  phone,  };

    /// If true, the sender is automatically generated by Customer.io.
    @BuiltValueField(wireName: r'auto_generated')
    bool? get autoGenerated;

    InlineResponse20050SenderIdentities._();

    @BuiltValueHook(initializeBuilder: true)
    static void _defaults(InlineResponse20050SenderIdentitiesBuilder b) => b;

    factory InlineResponse20050SenderIdentities([void updates(InlineResponse20050SenderIdentitiesBuilder b)]) = _$InlineResponse20050SenderIdentities;

    @BuiltValueSerializer(custom: true)
    static Serializer<InlineResponse20050SenderIdentities> get serializer => _$InlineResponse20050SenderIdentitiesSerializer();
}

class _$InlineResponse20050SenderIdentitiesSerializer implements StructuredSerializer<InlineResponse20050SenderIdentities> {
    @override
    final Iterable<Type> types = const [InlineResponse20050SenderIdentities, _$InlineResponse20050SenderIdentities];

    @override
    final String wireName = r'InlineResponse20050SenderIdentities';

    @override
    Iterable<Object?> serialize(Serializers serializers, InlineResponse20050SenderIdentities object,
        {FullType specifiedType = FullType.unspecified}) {
        final result = <Object?>[];
        if (object.id != null) {
            result
                ..add(r'id')
                ..add(serializers.serialize(object.id,
                    specifiedType: const FullType(int)));
        }
        if (object.deduplicateId != null) {
            result
                ..add(r'deduplicate_id')
                ..add(serializers.serialize(object.deduplicateId,
                    specifiedType: const FullType(String)));
        }
        if (object.name != null) {
            result
                ..add(r'name')
                ..add(serializers.serialize(object.name,
                    specifiedType: const FullType(String)));
        }
        if (object.email != null) {
            result
                ..add(r'email')
                ..add(serializers.serialize(object.email,
                    specifiedType: const FullType(String)));
        }
        if (object.address != null) {
            result
                ..add(r'address')
                ..add(serializers.serialize(object.address,
                    specifiedType: const FullType(String)));
        }
        if (object.templateType != null) {
            result
                ..add(r'template_type')
                ..add(serializers.serialize(object.templateType,
                    specifiedType: const FullType(InlineResponse20050SenderIdentitiesTemplateTypeEnum)));
        }
        if (object.autoGenerated != null) {
            result
                ..add(r'auto_generated')
                ..add(serializers.serialize(object.autoGenerated,
                    specifiedType: const FullType(bool)));
        }
        return result;
    }

    @override
    InlineResponse20050SenderIdentities deserialize(Serializers serializers, Iterable<Object?> serialized,
        {FullType specifiedType = FullType.unspecified}) {
        final result = InlineResponse20050SenderIdentitiesBuilder();

        final iterator = serialized.iterator;
        while (iterator.moveNext()) {
            final key = iterator.current as String;
            iterator.moveNext();
            final Object? value = iterator.current;
            
            switch (key) {
                case r'id':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(int)) as int;
                    result.id = valueDes;
                    break;
                case r'deduplicate_id':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.deduplicateId = valueDes;
                    break;
                case r'name':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.name = valueDes;
                    break;
                case r'email':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.email = valueDes;
                    break;
                case r'address':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.address = valueDes;
                    break;
                case r'template_type':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(InlineResponse20050SenderIdentitiesTemplateTypeEnum)) as InlineResponse20050SenderIdentitiesTemplateTypeEnum;
                    result.templateType = valueDes;
                    break;
                case r'auto_generated':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(bool)) as bool;
                    result.autoGenerated = valueDes;
                    break;
            }
        }
        return result.build();
    }
}

class InlineResponse20050SenderIdentitiesTemplateTypeEnum extends EnumClass {

  /// The type of sender.
  @BuiltValueEnumConst(wireName: r'email')
  static const InlineResponse20050SenderIdentitiesTemplateTypeEnum email = _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_email;
  /// The type of sender.
  @BuiltValueEnumConst(wireName: r'phone')
  static const InlineResponse20050SenderIdentitiesTemplateTypeEnum phone = _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_phone;

  static Serializer<InlineResponse20050SenderIdentitiesTemplateTypeEnum> get serializer => _$inlineResponse20050SenderIdentitiesTemplateTypeEnumSerializer;

  const InlineResponse20050SenderIdentitiesTemplateTypeEnum._(String name): super(name);

  static BuiltSet<InlineResponse20050SenderIdentitiesTemplateTypeEnum> get values => _$inlineResponse20050SenderIdentitiesTemplateTypeEnumValues;
  static InlineResponse20050SenderIdentitiesTemplateTypeEnum valueOf(String name) => _$inlineResponse20050SenderIdentitiesTemplateTypeEnumValueOf(name);
}

