// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'inline_response20050_sender_identities.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

const InlineResponse20050SenderIdentitiesTemplateTypeEnum
    _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_email =
    const InlineResponse20050SenderIdentitiesTemplateTypeEnum._('email');
const InlineResponse20050SenderIdentitiesTemplateTypeEnum
    _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_phone =
    const InlineResponse20050SenderIdentitiesTemplateTypeEnum._('phone');

InlineResponse20050SenderIdentitiesTemplateTypeEnum
    _$inlineResponse20050SenderIdentitiesTemplateTypeEnumValueOf(String name) {
  switch (name) {
    case 'email':
      return _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_email;
    case 'phone':
      return _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_phone;
    default:
      throw new ArgumentError(name);
  }
}

final BuiltSet<InlineResponse20050SenderIdentitiesTemplateTypeEnum>
    _$inlineResponse20050SenderIdentitiesTemplateTypeEnumValues =
    new BuiltSet<InlineResponse20050SenderIdentitiesTemplateTypeEnum>(const <
        InlineResponse20050SenderIdentitiesTemplateTypeEnum>[
  _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_email,
  _$inlineResponse20050SenderIdentitiesTemplateTypeEnum_phone,
]);

Serializer<InlineResponse20050SenderIdentitiesTemplateTypeEnum>
    _$inlineResponse20050SenderIdentitiesTemplateTypeEnumSerializer =
    new _$InlineResponse20050SenderIdentitiesTemplateTypeEnumSerializer();

class _$InlineResponse20050SenderIdentitiesTemplateTypeEnumSerializer
    implements
        PrimitiveSerializer<
            InlineResponse20050SenderIdentitiesTemplateTypeEnum> {
  static const Map<String, Object> _toWire = const <String, Object>{
    'email': 'email',
    'phone': 'phone',
  };
  static const Map<Object, String> _fromWire = const <Object, String>{
    'email': 'email',
    'phone': 'phone',
  };

  @override
  final Iterable<Type> types = const <Type>[
    InlineResponse20050SenderIdentitiesTemplateTypeEnum
  ];
  @override
  final String wireName = 'InlineResponse20050SenderIdentitiesTemplateTypeEnum';

  @override
  Object serialize(Serializers serializers,
          InlineResponse20050SenderIdentitiesTemplateTypeEnum object,
          {FullType specifiedType = FullType.unspecified}) =>
      _toWire[object.name] ?? object.name;

  @override
  InlineResponse20050SenderIdentitiesTemplateTypeEnum deserialize(
          Serializers serializers, Object serialized,
          {FullType specifiedType = FullType.unspecified}) =>
      InlineResponse20050SenderIdentitiesTemplateTypeEnum.valueOf(
          _fromWire[serialized] ?? (serialized is String ? serialized : ''));
}

class _$InlineResponse20050SenderIdentities
    extends InlineResponse20050SenderIdentities {
  @override
  final int? id;
  @override
  final String? deduplicateId;
  @override
  final String? name;
  @override
  final String? email;
  @override
  final String? address;
  @override
  final InlineResponse20050SenderIdentitiesTemplateTypeEnum? templateType;
  @override
  final bool? autoGenerated;

  factory _$InlineResponse20050SenderIdentities(
          [void Function(InlineResponse20050SenderIdentitiesBuilder)?
              updates]) =>
      (new InlineResponse20050SenderIdentitiesBuilder()..update(updates))
          .build();

  _$InlineResponse20050SenderIdentities._(
      {this.id,
      this.deduplicateId,
      this.name,
      this.email,
      this.address,
      this.templateType,
      this.autoGenerated})
      : super._();

  @override
  InlineResponse20050SenderIdentities rebuild(
          void Function(InlineResponse20050SenderIdentitiesBuilder) updates) =>
      (toBuilder()..update(updates)).build();

  @override
  InlineResponse20050SenderIdentitiesBuilder toBuilder() =>
      new InlineResponse20050SenderIdentitiesBuilder()..replace(this);

  @override
  bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is InlineResponse20050SenderIdentities &&
        id == other.id &&
        deduplicateId == other.deduplicateId &&
        name == other.name &&
        email == other.email &&
        address == other.address &&
        templateType == other.templateType &&
        autoGenerated == other.autoGenerated;
  }

  @override
  int get hashCode {
    return $jf($jc(
        $jc(
            $jc(
                $jc(
                    $jc($jc($jc(0, id.hashCode), deduplicateId.hashCode),
                        name.hashCode),
                    email.hashCode),
                address.hashCode),
            templateType.hashCode),
        autoGenerated.hashCode));
  }

  @override
  String toString() {
    return (newBuiltValueToStringHelper('InlineResponse20050SenderIdentities')
          ..add('id', id)
          ..add('deduplicateId', deduplicateId)
          ..add('name', name)
          ..add('email', email)
          ..add('address', address)
          ..add('templateType', templateType)
          ..add('autoGenerated', autoGenerated))
        .toString();
  }
}

class InlineResponse20050SenderIdentitiesBuilder
    implements
        Builder<InlineResponse20050SenderIdentities,
            InlineResponse20050SenderIdentitiesBuilder> {
  _$InlineResponse20050SenderIdentities? _$v;

  int? _id;
  int? get id => _$this._id;
  set id(int? id) => _$this._id = id;

  String? _deduplicateId;
  String? get deduplicateId => _$this._deduplicateId;
  set deduplicateId(String? deduplicateId) =>
      _$this._deduplicateId = deduplicateId;

  String? _name;
  String? get name => _$this._name;
  set name(String? name) => _$this._name = name;

  String? _email;
  String? get email => _$this._email;
  set email(String? email) => _$this._email = email;

  String? _address;
  String? get address => _$this._address;
  set address(String? address) => _$this._address = address;

  InlineResponse20050SenderIdentitiesTemplateTypeEnum? _templateType;
  InlineResponse20050SenderIdentitiesTemplateTypeEnum? get templateType =>
      _$this._templateType;
  set templateType(
          InlineResponse20050SenderIdentitiesTemplateTypeEnum? templateType) =>
      _$this._templateType = templateType;

  bool? _autoGenerated;
  bool? get autoGenerated => _$this._autoGenerated;
  set autoGenerated(bool? autoGenerated) =>
      _$this._autoGenerated = autoGenerated;

  InlineResponse20050SenderIdentitiesBuilder() {
    InlineResponse20050SenderIdentities._defaults(this);
  }

  InlineResponse20050SenderIdentitiesBuilder get _$this {
    final $v = _$v;
    if ($v != null) {
      _id = $v.id;
      _deduplicateId = $v.deduplicateId;
      _name = $v.name;
      _email = $v.email;
      _address = $v.address;
      _templateType = $v.templateType;
      _autoGenerated = $v.autoGenerated;
      _$v = null;
    }
    return this;
  }

  @override
  void replace(InlineResponse20050SenderIdentities other) {
    ArgumentError.checkNotNull(other, 'other');
    _$v = other as _$InlineResponse20050SenderIdentities;
  }

  @override
  void update(
      void Function(InlineResponse20050SenderIdentitiesBuilder)? updates) {
    if (updates != null) updates(this);
  }

  @override
  _$InlineResponse20050SenderIdentities build() {
    final _$result = _$v ??
        new _$InlineResponse20050SenderIdentities._(
            id: id,
            deduplicateId: deduplicateId,
            name: name,
            email: email,
            address: address,
            templateType: templateType,
            autoGenerated: autoGenerated);
    replace(_$result);
    return _$result;
  }
}

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,deprecated_member_use_from_same_package,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
