// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sender_identity_object.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

const SenderIdentityObjectTemplateTypeEnum
    _$senderIdentityObjectTemplateTypeEnum_email =
    const SenderIdentityObjectTemplateTypeEnum._('email');
const SenderIdentityObjectTemplateTypeEnum
    _$senderIdentityObjectTemplateTypeEnum_phone =
    const SenderIdentityObjectTemplateTypeEnum._('phone');

SenderIdentityObjectTemplateTypeEnum
    _$senderIdentityObjectTemplateTypeEnumValueOf(String name) {
  switch (name) {
    case 'email':
      return _$senderIdentityObjectTemplateTypeEnum_email;
    case 'phone':
      return _$senderIdentityObjectTemplateTypeEnum_phone;
    default:
      throw new ArgumentError(name);
  }
}

final BuiltSet<SenderIdentityObjectTemplateTypeEnum>
    _$senderIdentityObjectTemplateTypeEnumValues =
    new BuiltSet<SenderIdentityObjectTemplateTypeEnum>(const <
        SenderIdentityObjectTemplateTypeEnum>[
  _$senderIdentityObjectTemplateTypeEnum_email,
  _$senderIdentityObjectTemplateTypeEnum_phone,
]);

Serializer<SenderIdentityObjectTemplateTypeEnum>
    _$senderIdentityObjectTemplateTypeEnumSerializer =
    new _$SenderIdentityObjectTemplateTypeEnumSerializer();

class _$SenderIdentityObjectTemplateTypeEnumSerializer
    implements PrimitiveSerializer<SenderIdentityObjectTemplateTypeEnum> {
  static const Map<String, Object> _toWire = const <String, Object>{
    'email': 'email',
    'phone': 'phone',
  };
  static const Map<Object, String> _fromWire = const <Object, String>{
    'email': 'email',
    'phone': 'phone',
  };

  @override
  final Iterable<Type> types = const <Type>[
    SenderIdentityObjectTemplateTypeEnum
  ];
  @override
  final String wireName = 'SenderIdentityObjectTemplateTypeEnum';

  @override
  Object serialize(
          Serializers serializers, SenderIdentityObjectTemplateTypeEnum object,
          {FullType specifiedType = FullType.unspecified}) =>
      _toWire[object.name] ?? object.name;

  @override
  SenderIdentityObjectTemplateTypeEnum deserialize(
          Serializers serializers, Object serialized,
          {FullType specifiedType = FullType.unspecified}) =>
      SenderIdentityObjectTemplateTypeEnum.valueOf(
          _fromWire[serialized] ?? (serialized is String ? serialized : ''));
}

class _$SenderIdentityObject extends SenderIdentityObject {
  @override
  final int? id;
  @override
  final String? deduplicateId;
  @override
  final String? name;
  @override
  final String? email;
  @override
  final String? address;
  @override
  final SenderIdentityObjectTemplateTypeEnum? templateType;
  @override
  final bool? autoGenerated;

  factory _$SenderIdentityObject(
          [void Function(SenderIdentityObjectBuilder)? updates]) =>
      (new SenderIdentityObjectBuilder()..update(updates)).build();

  _$SenderIdentityObject._(
      {this.id,
      this.deduplicateId,
      this.name,
      this.email,
      this.address,
      this.templateType,
      this.autoGenerated})
      : super._();

  @override
  SenderIdentityObject rebuild(
          void Function(SenderIdentityObjectBuilder) updates) =>
      (toBuilder()..update(updates)).build();

  @override
  SenderIdentityObjectBuilder toBuilder() =>
      new SenderIdentityObjectBuilder()..replace(this);

  @override
  bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is SenderIdentityObject &&
        id == other.id &&
        deduplicateId == other.deduplicateId &&
        name == other.name &&
        email == other.email &&
        address == other.address &&
        templateType == other.templateType &&
        autoGenerated == other.autoGenerated;
  }

  @override
  int get hashCode {
    return $jf($jc(
        $jc(
            $jc(
                $jc(
                    $jc($jc($jc(0, id.hashCode), deduplicateId.hashCode),
                        name.hashCode),
                    email.hashCode),
                address.hashCode),
            templateType.hashCode),
        autoGenerated.hashCode));
  }

  @override
  String toString() {
    return (newBuiltValueToStringHelper('SenderIdentityObject')
          ..add('id', id)
          ..add('deduplicateId', deduplicateId)
          ..add('name', name)
          ..add('email', email)
          ..add('address', address)
          ..add('templateType', templateType)
          ..add('autoGenerated', autoGenerated))
        .toString();
  }
}

class SenderIdentityObjectBuilder
    implements Builder<SenderIdentityObject, SenderIdentityObjectBuilder> {
  _$SenderIdentityObject? _$v;

  int? _id;
  int? get id => _$this._id;
  set id(int? id) => _$this._id = id;

  String? _deduplicateId;
  String? get deduplicateId => _$this._deduplicateId;
  set deduplicateId(String? deduplicateId) =>
      _$this._deduplicateId = deduplicateId;

  String? _name;
  String? get name => _$this._name;
  set name(String? name) => _$this._name = name;

  String? _email;
  String? get email => _$this._email;
  set email(String? email) => _$this._email = email;

  String? _address;
  String? get address => _$this._address;
  set address(String? address) => _$this._address = address;

  SenderIdentityObjectTemplateTypeEnum? _templateType;
  SenderIdentityObjectTemplateTypeEnum? get templateType =>
      _$this._templateType;
  set templateType(SenderIdentityObjectTemplateTypeEnum? templateType) =>
      _$this._templateType = templateType;

  bool? _autoGenerated;
  bool? get autoGenerated => _$this._autoGenerated;
  set autoGenerated(bool? autoGenerated) =>
      _$this._autoGenerated = autoGenerated;

  SenderIdentityObjectBuilder() {
    SenderIdentityObject._defaults(this);
  }

  SenderIdentityObjectBuilder get _$this {
    final $v = _$v;
    if ($v != null) {
      _id = $v.id;
      _deduplicateId = $v.deduplicateId;
      _name = $v.name;
      _email = $v.email;
      _address = $v.address;
      _templateType = $v.templateType;
      _autoGenerated = $v.autoGenerated;
      _$v = null;
    }
    return this;
  }

  @override
  void replace(SenderIdentityObject other) {
    ArgumentError.checkNotNull(other, 'other');
    _$v = other as _$SenderIdentityObject;
  }

  @override
  void update(void Function(SenderIdentityObjectBuilder)? updates) {
    if (updates != null) updates(this);
  }

  @override
  _$SenderIdentityObject build() {
    final _$result = _$v ??
        new _$SenderIdentityObject._(
            id: id,
            deduplicateId: deduplicateId,
            name: name,
            email: email,
            address: address,
            templateType: templateType,
            autoGenerated: autoGenerated);
    replace(_$result);
    return _$result;
  }
}

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,deprecated_member_use_from_same_package,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
