//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'sender_identity_object.g.dart';

/// Information about a sender.
///
/// Properties:
/// * [id] - The identifier of a sender.
/// * [deduplicateId] - A completely unique CIO identifier.
/// * [name] - The name of the sender.
/// * [email] - The email address of the sender.
/// * [address] - The sender name and email address in the format `name undefined<name@example.com>`.
/// * [templateType] - The type of sender.
/// * [autoGenerated] - If true, the sender is automatically generated by Customer.io.
abstract class SenderIdentityObject implements Built<SenderIdentityObject, SenderIdentityObjectBuilder> {
    /// The identifier of a sender.
    @BuiltValueField(wireName: r'id')
    int? get id;

    /// A completely unique CIO identifier.
    @BuiltValueField(wireName: r'deduplicate_id')
    String? get deduplicateId;

    /// The name of the sender.
    @BuiltValueField(wireName: r'name')
    String? get name;

    /// The email address of the sender.
    @BuiltValueField(wireName: r'email')
    String? get email;

    /// The sender name and email address in the format `name undefined<name@example.com>`.
    @BuiltValueField(wireName: r'address')
    String? get address;

    /// The type of sender.
    @BuiltValueField(wireName: r'template_type')
    SenderIdentityObjectTemplateTypeEnum? get templateType;
    // enum templateTypeEnum {  email,  phone,  };

    /// If true, the sender is automatically generated by Customer.io.
    @BuiltValueField(wireName: r'auto_generated')
    bool? get autoGenerated;

    SenderIdentityObject._();

    @BuiltValueHook(initializeBuilder: true)
    static void _defaults(SenderIdentityObjectBuilder b) => b;

    factory SenderIdentityObject([void updates(SenderIdentityObjectBuilder b)]) = _$SenderIdentityObject;

    @BuiltValueSerializer(custom: true)
    static Serializer<SenderIdentityObject> get serializer => _$SenderIdentityObjectSerializer();
}

class _$SenderIdentityObjectSerializer implements StructuredSerializer<SenderIdentityObject> {
    @override
    final Iterable<Type> types = const [SenderIdentityObject, _$SenderIdentityObject];

    @override
    final String wireName = r'SenderIdentityObject';

    @override
    Iterable<Object?> serialize(Serializers serializers, SenderIdentityObject object,
        {FullType specifiedType = FullType.unspecified}) {
        final result = <Object?>[];
        if (object.id != null) {
            result
                ..add(r'id')
                ..add(serializers.serialize(object.id,
                    specifiedType: const FullType(int)));
        }
        if (object.deduplicateId != null) {
            result
                ..add(r'deduplicate_id')
                ..add(serializers.serialize(object.deduplicateId,
                    specifiedType: const FullType(String)));
        }
        if (object.name != null) {
            result
                ..add(r'name')
                ..add(serializers.serialize(object.name,
                    specifiedType: const FullType(String)));
        }
        if (object.email != null) {
            result
                ..add(r'email')
                ..add(serializers.serialize(object.email,
                    specifiedType: const FullType(String)));
        }
        if (object.address != null) {
            result
                ..add(r'address')
                ..add(serializers.serialize(object.address,
                    specifiedType: const FullType(String)));
        }
        if (object.templateType != null) {
            result
                ..add(r'template_type')
                ..add(serializers.serialize(object.templateType,
                    specifiedType: const FullType(SenderIdentityObjectTemplateTypeEnum)));
        }
        if (object.autoGenerated != null) {
            result
                ..add(r'auto_generated')
                ..add(serializers.serialize(object.autoGenerated,
                    specifiedType: const FullType(bool)));
        }
        return result;
    }

    @override
    SenderIdentityObject deserialize(Serializers serializers, Iterable<Object?> serialized,
        {FullType specifiedType = FullType.unspecified}) {
        final result = SenderIdentityObjectBuilder();

        final iterator = serialized.iterator;
        while (iterator.moveNext()) {
            final key = iterator.current as String;
            iterator.moveNext();
            final Object? value = iterator.current;
            
            switch (key) {
                case r'id':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(int)) as int;
                    result.id = valueDes;
                    break;
                case r'deduplicate_id':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.deduplicateId = valueDes;
                    break;
                case r'name':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.name = valueDes;
                    break;
                case r'email':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.email = valueDes;
                    break;
                case r'address':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(String)) as String;
                    result.address = valueDes;
                    break;
                case r'template_type':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(SenderIdentityObjectTemplateTypeEnum)) as SenderIdentityObjectTemplateTypeEnum;
                    result.templateType = valueDes;
                    break;
                case r'auto_generated':
                    final valueDes = serializers.deserialize(value,
                        specifiedType: const FullType(bool)) as bool;
                    result.autoGenerated = valueDes;
                    break;
            }
        }
        return result.build();
    }
}

class SenderIdentityObjectTemplateTypeEnum extends EnumClass {

  /// The type of sender.
  @BuiltValueEnumConst(wireName: r'email')
  static const SenderIdentityObjectTemplateTypeEnum email = _$senderIdentityObjectTemplateTypeEnum_email;
  /// The type of sender.
  @BuiltValueEnumConst(wireName: r'phone')
  static const SenderIdentityObjectTemplateTypeEnum phone = _$senderIdentityObjectTemplateTypeEnum_phone;

  static Serializer<SenderIdentityObjectTemplateTypeEnum> get serializer => _$senderIdentityObjectTemplateTypeEnumSerializer;

  const SenderIdentityObjectTemplateTypeEnum._(String name): super(name);

  static BuiltSet<SenderIdentityObjectTemplateTypeEnum> get values => _$senderIdentityObjectTemplateTypeEnumValues;
  static SenderIdentityObjectTemplateTypeEnum valueOf(String name) => _$senderIdentityObjectTemplateTypeEnumValueOf(name);
}

